apiVersion: apps/v1
kind: Deployment
metadata:
  name: lower-deployment
  labels:
    app: lower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lower
  template:
    metadata:
      labels:
        app: lower
    spec:
      containers:
      - name: lower
        image: mahdyy/lower
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: lower-service
  labels:
    app: lower
spec:
  selector:
    app:  lower
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 5000
      nodePort: 30002