apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-deployment
  labels:
    app: sum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sum
  template:
    metadata:
      labels:
        app: sum
    spec:
      containers:
      - name: sum
        image: mahdyy/sum
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: sum-service
  labels:
    app: sum
spec:
  selector:
    app:  sum
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 5000
      nodePort: 30001